// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: protobuf/BookLibraryService.proto

package bookservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookLibraryClient is the client API for BookLibrary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookLibraryClient interface {
	GetBookStatus(ctx context.Context, in *BookId, opts ...grpc.CallOption) (*BookState, error)
	GetAllBookLocations(ctx context.Context, in *BookId, opts ...grpc.CallOption) (BookLibrary_GetAllBookLocationsClient, error)
}

type bookLibraryClient struct {
	cc grpc.ClientConnInterface
}

func NewBookLibraryClient(cc grpc.ClientConnInterface) BookLibraryClient {
	return &bookLibraryClient{cc}
}

func (c *bookLibraryClient) GetBookStatus(ctx context.Context, in *BookId, opts ...grpc.CallOption) (*BookState, error) {
	out := new(BookState)
	err := c.cc.Invoke(ctx, "/BookService.BookLibrary/GetBookStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookLibraryClient) GetAllBookLocations(ctx context.Context, in *BookId, opts ...grpc.CallOption) (BookLibrary_GetAllBookLocationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookLibrary_ServiceDesc.Streams[0], "/BookService.BookLibrary/GetAllBookLocations", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookLibraryGetAllBookLocationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookLibrary_GetAllBookLocationsClient interface {
	Recv() (*Location, error)
	grpc.ClientStream
}

type bookLibraryGetAllBookLocationsClient struct {
	grpc.ClientStream
}

func (x *bookLibraryGetAllBookLocationsClient) Recv() (*Location, error) {
	m := new(Location)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookLibraryServer is the server API for BookLibrary service.
// All implementations must embed UnimplementedBookLibraryServer
// for forward compatibility
type BookLibraryServer interface {
	GetBookStatus(context.Context, *BookId) (*BookState, error)
	GetAllBookLocations(*BookId, BookLibrary_GetAllBookLocationsServer) error
	mustEmbedUnimplementedBookLibraryServer()
}

// UnimplementedBookLibraryServer must be embedded to have forward compatible implementations.
type UnimplementedBookLibraryServer struct {
}

func (UnimplementedBookLibraryServer) GetBookStatus(context.Context, *BookId) (*BookState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookStatus not implemented")
}
func (UnimplementedBookLibraryServer) GetAllBookLocations(*BookId, BookLibrary_GetAllBookLocationsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllBookLocations not implemented")
}
func (UnimplementedBookLibraryServer) mustEmbedUnimplementedBookLibraryServer() {}

// UnsafeBookLibraryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookLibraryServer will
// result in compilation errors.
type UnsafeBookLibraryServer interface {
	mustEmbedUnimplementedBookLibraryServer()
}

func RegisterBookLibraryServer(s grpc.ServiceRegistrar, srv BookLibraryServer) {
	s.RegisterService(&BookLibrary_ServiceDesc, srv)
}

func _BookLibrary_GetBookStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookLibraryServer).GetBookStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookService.BookLibrary/GetBookStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookLibraryServer).GetBookStatus(ctx, req.(*BookId))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookLibrary_GetAllBookLocations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BookId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookLibraryServer).GetAllBookLocations(m, &bookLibraryGetAllBookLocationsServer{stream})
}

type BookLibrary_GetAllBookLocationsServer interface {
	Send(*Location) error
	grpc.ServerStream
}

type bookLibraryGetAllBookLocationsServer struct {
	grpc.ServerStream
}

func (x *bookLibraryGetAllBookLocationsServer) Send(m *Location) error {
	return x.ServerStream.SendMsg(m)
}

// BookLibrary_ServiceDesc is the grpc.ServiceDesc for BookLibrary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookLibrary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BookService.BookLibrary",
	HandlerType: (*BookLibraryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookStatus",
			Handler:    _BookLibrary_GetBookStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllBookLocations",
			Handler:       _BookLibrary_GetAllBookLocations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/BookLibraryService.proto",
}
