// protoc --cpp_out=AsyncClient\ --go_out=server\ protobuf\BookLibraryService.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: protobuf/BookLibraryService.proto

package bookservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookStateEnum int32

const (
	BookStateEnum_Unavailable BookStateEnum = 0
	BookStateEnum_Available   BookStateEnum = 1
	BookStateEnum_Reserved    BookStateEnum = 2
)

// Enum value maps for BookStateEnum.
var (
	BookStateEnum_name = map[int32]string{
		0: "Unavailable",
		1: "Available",
		2: "Reserved",
	}
	BookStateEnum_value = map[string]int32{
		"Unavailable": 0,
		"Available":   1,
		"Reserved":    2,
	}
)

func (x BookStateEnum) Enum() *BookStateEnum {
	p := new(BookStateEnum)
	*p = x
	return p
}

func (x BookStateEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookStateEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_BookLibraryService_proto_enumTypes[0].Descriptor()
}

func (BookStateEnum) Type() protoreflect.EnumType {
	return &file_protobuf_BookLibraryService_proto_enumTypes[0]
}

func (x BookStateEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookStateEnum.Descriptor instead.
func (BookStateEnum) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_BookLibraryService_proto_rawDescGZIP(), []int{0}
}

type BookId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BookId) Reset() {
	*x = BookId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_BookLibraryService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookId) ProtoMessage() {}

func (x *BookId) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_BookLibraryService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookId.ProtoReflect.Descriptor instead.
func (*BookId) Descriptor() ([]byte, []int) {
	return file_protobuf_BookLibraryService_proto_rawDescGZIP(), []int{0}
}

func (x *BookId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BookState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    BookStateEnum `protobuf:"varint,1,opt,name=state,proto3,enum=BookService.BookStateEnum" json:"state,omitempty"`
	Location []string      `protobuf:"bytes,2,rep,name=location,proto3" json:"location,omitempty"` // If Available: Where is the book available
	User     *string       `protobuf:"bytes,3,opt,name=user,proto3,oneof" json:"user,omitempty"`   // If Reserved: Who is the last person who reserved the book
}

func (x *BookState) Reset() {
	*x = BookState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_BookLibraryService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookState) ProtoMessage() {}

func (x *BookState) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_BookLibraryService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookState.ProtoReflect.Descriptor instead.
func (*BookState) Descriptor() ([]byte, []int) {
	return file_protobuf_BookLibraryService_proto_rawDescGZIP(), []int{1}
}

func (x *BookState) GetState() BookStateEnum {
	if x != nil {
		return x.State
	}
	return BookStateEnum_Unavailable
}

func (x *BookState) GetLocation() []string {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *BookState) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_BookLibraryService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_BookLibraryService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_protobuf_BookLibraryService_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_protobuf_BookLibraryService_proto protoreflect.FileDescriptor

var file_protobuf_BookLibraryService_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x42, 0x6f, 0x6f, 0x6b, 0x4c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x18, 0x0a, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7b, 0x0a, 0x09, 0x42, 0x6f,
	0x6f, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x75, 0x6d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2a,
	0x3d, 0x0a, 0x0d, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d,
	0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x10, 0x02, 0x32, 0x94,
	0x01, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12, 0x3e,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x13, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x13, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x1a, 0x15, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x00, 0x30, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x66, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_BookLibraryService_proto_rawDescOnce sync.Once
	file_protobuf_BookLibraryService_proto_rawDescData = file_protobuf_BookLibraryService_proto_rawDesc
)

func file_protobuf_BookLibraryService_proto_rawDescGZIP() []byte {
	file_protobuf_BookLibraryService_proto_rawDescOnce.Do(func() {
		file_protobuf_BookLibraryService_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_BookLibraryService_proto_rawDescData)
	})
	return file_protobuf_BookLibraryService_proto_rawDescData
}

var file_protobuf_BookLibraryService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_BookLibraryService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_BookLibraryService_proto_goTypes = []interface{}{
	(BookStateEnum)(0), // 0: BookService.BookStateEnum
	(*BookId)(nil),     // 1: BookService.BookId
	(*BookState)(nil),  // 2: BookService.BookState
	(*Location)(nil),   // 3: BookService.Location
}
var file_protobuf_BookLibraryService_proto_depIdxs = []int32{
	0, // 0: BookService.BookState.state:type_name -> BookService.BookStateEnum
	1, // 1: BookService.BookLibrary.GetBookStatus:input_type -> BookService.BookId
	1, // 2: BookService.BookLibrary.GetAllBookLocations:input_type -> BookService.BookId
	2, // 3: BookService.BookLibrary.GetBookStatus:output_type -> BookService.BookState
	3, // 4: BookService.BookLibrary.GetAllBookLocations:output_type -> BookService.Location
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_BookLibraryService_proto_init() }
func file_protobuf_BookLibraryService_proto_init() {
	if File_protobuf_BookLibraryService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_BookLibraryService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_BookLibraryService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_BookLibraryService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_BookLibraryService_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_BookLibraryService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_BookLibraryService_proto_goTypes,
		DependencyIndexes: file_protobuf_BookLibraryService_proto_depIdxs,
		EnumInfos:         file_protobuf_BookLibraryService_proto_enumTypes,
		MessageInfos:      file_protobuf_BookLibraryService_proto_msgTypes,
	}.Build()
	File_protobuf_BookLibraryService_proto = out.File
	file_protobuf_BookLibraryService_proto_rawDesc = nil
	file_protobuf_BookLibraryService_proto_goTypes = nil
	file_protobuf_BookLibraryService_proto_depIdxs = nil
}
