// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protobuf/BookLibraryService.proto

#include "protobuf/BookLibraryService.pb.h"
#include "protobuf/BookLibraryService.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace BookService {

static const char* BookLibrary_method_names[] = {
  "/BookService.BookLibrary/GetBookStatus",
  "/BookService.BookLibrary/MakeBookReservation",
  "/BookService.BookLibrary/ReturnBookReservation",
};

std::unique_ptr< BookLibrary::Stub> BookLibrary::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BookLibrary::Stub> stub(new BookLibrary::Stub(channel, options));
  return stub;
}

BookLibrary::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetBookStatus_(BookLibrary_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MakeBookReservation_(BookLibrary_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReturnBookReservation_(BookLibrary_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BookLibrary::Stub::GetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId& request, ::BookService::BookState* response) {
  return ::grpc::internal::BlockingUnaryCall< ::BookService::BookId, ::BookService::BookState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetBookStatus_, context, request, response);
}

void BookLibrary::Stub::async::GetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId* request, ::BookService::BookState* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::BookService::BookId, ::BookService::BookState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBookStatus_, context, request, response, std::move(f));
}

void BookLibrary::Stub::async::GetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId* request, ::BookService::BookState* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBookStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::BookService::BookState>* BookLibrary::Stub::PrepareAsyncGetBookStatusRaw(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::BookService::BookState, ::BookService::BookId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetBookStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::BookService::BookState>* BookLibrary::Stub::AsyncGetBookStatusRaw(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetBookStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BookLibrary::Stub::MakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::BookService::BookState* response) {
  return ::grpc::internal::BlockingUnaryCall< ::BookService::BookReservation, ::BookService::BookState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MakeBookReservation_, context, request, response);
}

void BookLibrary::Stub::async::MakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation* request, ::BookService::BookState* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::BookService::BookReservation, ::BookService::BookState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MakeBookReservation_, context, request, response, std::move(f));
}

void BookLibrary::Stub::async::MakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation* request, ::BookService::BookState* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MakeBookReservation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::BookService::BookState>* BookLibrary::Stub::PrepareAsyncMakeBookReservationRaw(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::BookService::BookState, ::BookService::BookReservation, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MakeBookReservation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::BookService::BookState>* BookLibrary::Stub::AsyncMakeBookReservationRaw(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMakeBookReservationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BookLibrary::Stub::ReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::BookService::BookState* response) {
  return ::grpc::internal::BlockingUnaryCall< ::BookService::ReturnBook, ::BookService::BookState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReturnBookReservation_, context, request, response);
}

void BookLibrary::Stub::async::ReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook* request, ::BookService::BookState* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::BookService::ReturnBook, ::BookService::BookState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReturnBookReservation_, context, request, response, std::move(f));
}

void BookLibrary::Stub::async::ReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook* request, ::BookService::BookState* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReturnBookReservation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::BookService::BookState>* BookLibrary::Stub::PrepareAsyncReturnBookReservationRaw(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::BookService::BookState, ::BookService::ReturnBook, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReturnBookReservation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::BookService::BookState>* BookLibrary::Stub::AsyncReturnBookReservationRaw(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReturnBookReservationRaw(context, request, cq);
  result->StartCall();
  return result;
}

BookLibrary::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BookLibrary_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BookLibrary::Service, ::BookService::BookId, ::BookService::BookState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BookLibrary::Service* service,
             ::grpc::ServerContext* ctx,
             const ::BookService::BookId* req,
             ::BookService::BookState* resp) {
               return service->GetBookStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BookLibrary_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BookLibrary::Service, ::BookService::BookReservation, ::BookService::BookState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BookLibrary::Service* service,
             ::grpc::ServerContext* ctx,
             const ::BookService::BookReservation* req,
             ::BookService::BookState* resp) {
               return service->MakeBookReservation(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BookLibrary_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BookLibrary::Service, ::BookService::ReturnBook, ::BookService::BookState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BookLibrary::Service* service,
             ::grpc::ServerContext* ctx,
             const ::BookService::ReturnBook* req,
             ::BookService::BookState* resp) {
               return service->ReturnBookReservation(ctx, req, resp);
             }, this)));
}

BookLibrary::Service::~Service() {
}

::grpc::Status BookLibrary::Service::GetBookStatus(::grpc::ServerContext* context, const ::BookService::BookId* request, ::BookService::BookState* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BookLibrary::Service::MakeBookReservation(::grpc::ServerContext* context, const ::BookService::BookReservation* request, ::BookService::BookState* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BookLibrary::Service::ReturnBookReservation(::grpc::ServerContext* context, const ::BookService::ReturnBook* request, ::BookService::BookState* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace BookService

