// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protobuf/BookLibraryService.proto
#ifndef GRPC_protobuf_2fBookLibraryService_2eproto__INCLUDED
#define GRPC_protobuf_2fBookLibraryService_2eproto__INCLUDED

#include "protobuf/BookLibraryService.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace BookService {

class BookLibrary final {
 public:
  static constexpr char const* service_full_name() {
    return "BookService.BookLibrary";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId& request, ::BookService::BookState* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>> AsyncGetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>>(AsyncGetBookStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>> PrepareAsyncGetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>>(PrepareAsyncGetBookStatusRaw(context, request, cq));
    }
    virtual ::grpc::Status MakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::BookService::BookState* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>> AsyncMakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>>(AsyncMakeBookReservationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>> PrepareAsyncMakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>>(PrepareAsyncMakeBookReservationRaw(context, request, cq));
    }
    virtual ::grpc::Status ReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::BookService::BookState* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>> AsyncReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>>(AsyncReturnBookReservationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>> PrepareAsyncReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>>(PrepareAsyncReturnBookReservationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId* request, ::BookService::BookState* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId* request, ::BookService::BookState* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void MakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation* request, ::BookService::BookState* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation* request, ::BookService::BookState* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook* request, ::BookService::BookState* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook* request, ::BookService::BookState* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>* AsyncGetBookStatusRaw(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>* PrepareAsyncGetBookStatusRaw(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>* AsyncMakeBookReservationRaw(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>* PrepareAsyncMakeBookReservationRaw(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>* AsyncReturnBookReservationRaw(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BookService::BookState>* PrepareAsyncReturnBookReservationRaw(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId& request, ::BookService::BookState* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>> AsyncGetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>>(AsyncGetBookStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>> PrepareAsyncGetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>>(PrepareAsyncGetBookStatusRaw(context, request, cq));
    }
    ::grpc::Status MakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::BookService::BookState* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>> AsyncMakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>>(AsyncMakeBookReservationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>> PrepareAsyncMakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>>(PrepareAsyncMakeBookReservationRaw(context, request, cq));
    }
    ::grpc::Status ReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::BookService::BookState* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>> AsyncReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>>(AsyncReturnBookReservationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>> PrepareAsyncReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BookService::BookState>>(PrepareAsyncReturnBookReservationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId* request, ::BookService::BookState* response, std::function<void(::grpc::Status)>) override;
      void GetBookStatus(::grpc::ClientContext* context, const ::BookService::BookId* request, ::BookService::BookState* response, ::grpc::ClientUnaryReactor* reactor) override;
      void MakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation* request, ::BookService::BookState* response, std::function<void(::grpc::Status)>) override;
      void MakeBookReservation(::grpc::ClientContext* context, const ::BookService::BookReservation* request, ::BookService::BookState* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook* request, ::BookService::BookState* response, std::function<void(::grpc::Status)>) override;
      void ReturnBookReservation(::grpc::ClientContext* context, const ::BookService::ReturnBook* request, ::BookService::BookState* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::BookService::BookState>* AsyncGetBookStatusRaw(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::BookService::BookState>* PrepareAsyncGetBookStatusRaw(::grpc::ClientContext* context, const ::BookService::BookId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::BookService::BookState>* AsyncMakeBookReservationRaw(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::BookService::BookState>* PrepareAsyncMakeBookReservationRaw(::grpc::ClientContext* context, const ::BookService::BookReservation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::BookService::BookState>* AsyncReturnBookReservationRaw(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::BookService::BookState>* PrepareAsyncReturnBookReservationRaw(::grpc::ClientContext* context, const ::BookService::ReturnBook& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetBookStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_MakeBookReservation_;
    const ::grpc::internal::RpcMethod rpcmethod_ReturnBookReservation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetBookStatus(::grpc::ServerContext* context, const ::BookService::BookId* request, ::BookService::BookState* response);
    virtual ::grpc::Status MakeBookReservation(::grpc::ServerContext* context, const ::BookService::BookReservation* request, ::BookService::BookState* response);
    virtual ::grpc::Status ReturnBookReservation(::grpc::ServerContext* context, const ::BookService::ReturnBook* request, ::BookService::BookState* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetBookStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetBookStatus() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetBookStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBookStatus(::grpc::ServerContext* /*context*/, const ::BookService::BookId* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBookStatus(::grpc::ServerContext* context, ::BookService::BookId* request, ::grpc::ServerAsyncResponseWriter< ::BookService::BookState>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_MakeBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MakeBookReservation() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_MakeBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::BookReservation* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMakeBookReservation(::grpc::ServerContext* context, ::BookService::BookReservation* request, ::grpc::ServerAsyncResponseWriter< ::BookService::BookState>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReturnBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReturnBookReservation() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ReturnBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReturnBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::ReturnBook* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReturnBookReservation(::grpc::ServerContext* context, ::BookService::ReturnBook* request, ::grpc::ServerAsyncResponseWriter< ::BookService::BookState>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetBookStatus<WithAsyncMethod_MakeBookReservation<WithAsyncMethod_ReturnBookReservation<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetBookStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetBookStatus() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::BookService::BookId, ::BookService::BookState>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::BookService::BookId* request, ::BookService::BookState* response) { return this->GetBookStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetBookStatus(
        ::grpc::MessageAllocator< ::BookService::BookId, ::BookService::BookState>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::BookService::BookId, ::BookService::BookState>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetBookStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBookStatus(::grpc::ServerContext* /*context*/, const ::BookService::BookId* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBookStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::BookService::BookId* /*request*/, ::BookService::BookState* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_MakeBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MakeBookReservation() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::BookService::BookReservation, ::BookService::BookState>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::BookService::BookReservation* request, ::BookService::BookState* response) { return this->MakeBookReservation(context, request, response); }));}
    void SetMessageAllocatorFor_MakeBookReservation(
        ::grpc::MessageAllocator< ::BookService::BookReservation, ::BookService::BookState>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::BookService::BookReservation, ::BookService::BookState>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_MakeBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::BookReservation* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MakeBookReservation(
      ::grpc::CallbackServerContext* /*context*/, const ::BookService::BookReservation* /*request*/, ::BookService::BookState* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReturnBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReturnBookReservation() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::BookService::ReturnBook, ::BookService::BookState>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::BookService::ReturnBook* request, ::BookService::BookState* response) { return this->ReturnBookReservation(context, request, response); }));}
    void SetMessageAllocatorFor_ReturnBookReservation(
        ::grpc::MessageAllocator< ::BookService::ReturnBook, ::BookService::BookState>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::BookService::ReturnBook, ::BookService::BookState>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReturnBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReturnBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::ReturnBook* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReturnBookReservation(
      ::grpc::CallbackServerContext* /*context*/, const ::BookService::ReturnBook* /*request*/, ::BookService::BookState* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetBookStatus<WithCallbackMethod_MakeBookReservation<WithCallbackMethod_ReturnBookReservation<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetBookStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetBookStatus() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetBookStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBookStatus(::grpc::ServerContext* /*context*/, const ::BookService::BookId* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_MakeBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MakeBookReservation() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_MakeBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::BookReservation* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReturnBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReturnBookReservation() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ReturnBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReturnBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::ReturnBook* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetBookStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetBookStatus() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetBookStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBookStatus(::grpc::ServerContext* /*context*/, const ::BookService::BookId* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBookStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_MakeBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MakeBookReservation() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_MakeBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::BookReservation* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMakeBookReservation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReturnBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReturnBookReservation() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ReturnBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReturnBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::ReturnBook* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReturnBookReservation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetBookStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetBookStatus() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetBookStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetBookStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBookStatus(::grpc::ServerContext* /*context*/, const ::BookService::BookId* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBookStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MakeBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MakeBookReservation() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->MakeBookReservation(context, request, response); }));
    }
    ~WithRawCallbackMethod_MakeBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::BookReservation* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MakeBookReservation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReturnBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReturnBookReservation() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReturnBookReservation(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReturnBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReturnBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::ReturnBook* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReturnBookReservation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetBookStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetBookStatus() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::BookService::BookId, ::BookService::BookState>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::BookService::BookId, ::BookService::BookState>* streamer) {
                       return this->StreamedGetBookStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetBookStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetBookStatus(::grpc::ServerContext* /*context*/, const ::BookService::BookId* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetBookStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::BookService::BookId,::BookService::BookState>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MakeBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_MakeBookReservation() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::BookService::BookReservation, ::BookService::BookState>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::BookService::BookReservation, ::BookService::BookState>* streamer) {
                       return this->StreamedMakeBookReservation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_MakeBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MakeBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::BookReservation* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMakeBookReservation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::BookService::BookReservation,::BookService::BookState>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReturnBookReservation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReturnBookReservation() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::BookService::ReturnBook, ::BookService::BookState>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::BookService::ReturnBook, ::BookService::BookState>* streamer) {
                       return this->StreamedReturnBookReservation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReturnBookReservation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReturnBookReservation(::grpc::ServerContext* /*context*/, const ::BookService::ReturnBook* /*request*/, ::BookService::BookState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReturnBookReservation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::BookService::ReturnBook,::BookService::BookState>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetBookStatus<WithStreamedUnaryMethod_MakeBookReservation<WithStreamedUnaryMethod_ReturnBookReservation<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetBookStatus<WithStreamedUnaryMethod_MakeBookReservation<WithStreamedUnaryMethod_ReturnBookReservation<Service > > > StreamedService;
};

}  // namespace BookService


#endif  // GRPC_protobuf_2fBookLibraryService_2eproto__INCLUDED
